# Generated by Django 4.2 on 2023-04-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=15)),
                ('lname', models.CharField(max_length=16)),
                ('birthday', models.CharField(max_length=6)),
                ('gender', models.CharField(max_length=6)),
                ('LOCATION', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=20)),
                ('icode', models.CharField(max_length=10)),
                ('phone1', models.CharField(max_length=15)),
                ('phone2', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
