# Generated by Django 4.2 on 2023-04-28 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('genq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_account',
            old_name='birthday',
            new_name='DOB',
        ),
        migrations.AddField(
            model_name='user_account',
            name='vtown',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_account',
            name='fname',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='user_account',
            name='icode',
            field=models.CharField(max_length=15),
        ),
    ]
